


brew "cloudflared"
brew "fswatch"
brew "fx"
brew "gh"
brew "git"
brew "git-delta"
brew "go"
brew "gopls"
brew "iperf3"
brew "jpeg-turbo"
brew "jq"
brew "lastpass-cli"
brew "mas"
brew "nvm"
brew "podman"
brew "poppler"
brew "rsync"
brew "sf"
brew "sqlc"
brew "step"
brew "supabase/tap/supabase"
brew "tesseract"
brew "tree"
brew "unar"
brew "vhs"
brew "zig"
brew "oven-sh/bun/bun"
cask "acorn"
cask "codex"
cask "discord"
cask "docker-desktop"
cask "elgato-stream-deck"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "goreleaser/tap/goreleaser"
cask "jetbrains-toolbox"
cask "lastpass"
cask "logi-options+"
cask "macs-fan-control"
cask "microsoft-edge"
cask "microsoft-teams"
cask "podman-desktop"
cask "rapidapi"
cask "rectangle"
cask "repo-prompt"
cask "shottr"
cask "soulver"
cask "timing"
cask "typora"
cask "visual-studio-code"
cask "whatsapp"
cask "zed"
cash "oven-sh/bun"
mas "Bear", id: 1091189122
mas "LastPass for Safari", id: 6504626762
mas "RetroClip", id: 1332064978
mas "Slack", id: 803453959
mas "Soulver 3", id: 1508732804
tap "goreleaser/tap"
tap "supabase/tap"
