tap "supabase/tap"

brew "lastpass-cli"
brew "git"
brew "podman"
brew "nvm"
brew "supabase/tap/supabase"
brew "podman"
brew "tree"
brew "gh"

cask "google-chrome"
cask "zed"
cask "lastpass"
cask "shottr"
cask "whatsapp"
cask "microsoft-edge"
cask "visual-studio-code"
cask "jetbrains-toolbox"
cask "podman-desktop"
cask "timing"
cask "docker"