# --- Quality of life ---
set -g history-limit 100000
set -g mouse on
set -g set-clipboard on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
setw -g automatic-rename off
setw -g allow-rename off
set -g mode-keys emacs

# Copy selected mouse text directly to macOS clipboard.
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Keyboard copy -> macOS clipboard (emacs copy-mode)
bind-key -T copy-mode Enter send -X copy-pipe-and-cancel "pbcopy"

# If I wanted it to be Alt-w
# bind-key -T copy-mode M-w   send -X copy-pipe-and-cancel "pbcopy"

# If I wanted it to be Ctrl-w
bind-key -T copy-mode C-w   send -X copy-pipe-and-cancel "pbcopy"
