# --- Reload ---
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# --- Prefix splits/navigation ---
bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L 5
bind J resize-pane -D 3
bind K resize-pane -U 3
bind L resize-pane -R 5
bind n next-window
bind p previous-window
