#!/usr/bin/env zsh
# .zprofile is sourced for login shells
# It's the recommended place to set environment variables
# required by login shells and initialization commands that
# should run only once

# TODO: Update these to print an error when not available.
#       Rethink nested else statements
# Choose correct Homebrew for this CPU
if [[ "$(uname -m)" == "arm64" ]]; then
  # Apple Silicon
  if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
else
  # TODO: Ensure we are on Intel
  # Intel
  if [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  fi
fi

